name: Release Charts

on:
  push:
    branches:
      - develop

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        run: | 
          - mkdir -p ./rr-proxy
          - ls ./rr-proxy
          - mkdir -p ./rr-proxy/release
          - "echo \"User-Agent: *\nDisallow: /\" > ./rr-proxy/robots.txt"
          - helm dependency update helm/pci
          - helm package helm/pci
          - cp -r index.html ./rr-proxy/release
          - helm repo index --url https://${CI_PROJECT_NAMESPACE}.gitlab.io/${CI_PROJECT_NAME}/release .
          - mv index.yaml ./rr-proxy/release
          - mv *.tgz ./rr-proxy/release
          - "pwd"
          - "echo  https://${CI_PROJECT_NAMESPACE}.gitlab.io/${CI_PROJECT_NAME}/release"
          - "ls"
          - "ls ./rr-proxy"
          - "cat ./rr-proxy/release/index.yaml"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"