name: Release Charts

on:
  push:
    branches:
      - develop

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: run the commands
        run: | 
            mkdir -p ./rr-proxy
            "ls"
            mkdir -p ./rr-proxy/release
            "pwd"
            "ls"
            helm dependency update rr-proxy
            helm package rr-proxy
            helm repo index --url https://91social.github.io/roadrunner-helm/ .
            mv *.tgz ./rr-proxy/roadrunner-helm
            "pwd"
            "ls"
      - uses: mathiasvr/command-output@v1
        continue-on-error: true
        id: cmd
        with:
         run: cat index.yaml
      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: roadrunner-proxy-0.1.0.tgz 

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
         name: assets-for-download
      - name: unzip artifact for deployment
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq roadrunner-proxy-0.1.0.tgz -d roadrunner-proxy

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      
    if: github.ref == 'refs/heads/develop


     
